version: "3.9"  # optional since v1.27.0
services:
  web_api:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./source/app:/app/app
    depends_on:
      - db
      - db_testing
    env_file:
      - .env
    environment:
      - POSTGRES_TEST_SERVER=db_testing
      - LOCAL=False
  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  db_testing:
    image: postgres:12
    volumes:
      - app-db-testing-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db_testing
      - PGDATA=/var/lib/postgresql/data/pgdata
volumes:
  app-db-data:
  app-db-testing-data:
